        std_program              GLint           0
        std_fragmentShader       GLuint          0
        std_vertexShader         GLuint          0

        stat_program             GLint           0
        stat_fragmentShader      GLuint          0
        stat_vertexShader        GLuint          0

        mainTextID               GLuint          0
        tankTextID               GLuint          0

        std_frShaderFilePath     db              "Resources/stdFragment.glsl", 0
        std_vrtxShaderFilePath   db              "Resources/stdVertex.glsl", 0

        stat_frShaderFilePath    db              "Resources/staticFragment.glsl", 0
        stat_vrtxShaderFilePath  db              "Resources/staticVertex.glsl", 0