        modelViewMatrixLocation         GLint   ?
        modelname                       db      "u_ModelViewMatrix",0

        projMatrixLocation              GLint   ?
        projname                         db      "u_ProjectionMatrix",0

        samplerLocation                 GLint   ?
        texname                         db      "texture1",0

        lightDirLocation                GLint   ?
        LDName                          db      "lightDir",0

        viewPosLocation                 GLint   ?
        VPName                          db      "viewPos",0

        lightColorLocation              GLint   ?
        LCName                          db      "lightColor",0