        modelMatrixLocation             GLint   ?
        modelMtrxName                   db      "u_ModelMatrix",0

        viewMatrixLocation              GLint   ?
        viewMtrxName                    db      "u_ViewMatrix",0

        projMatrixLocation              GLint   ?
        projMtrxName                    db      "u_ProjectionMatrix",0

        samplerLocation                 GLint   ?
        textName                        db      "texture1",0

        lightDirLocation                GLint   ?
        LDName                          db      "lightDir",0

        viewPosLocation                 GLint   ?
        VPName                          db      "viewPos",0

        lightColorLocation              GLint   ?
        LCName                          db      "lightColor",0