mainCamera              dd                      ?

stdOffset               Vector3                 0.0, 1.5, 0.0


position                Vector3                 2.0, 2.0, -2.0
turn                    Vector3                 40.0, 0.0, 0.0

mouseSpeed              GLfloat                 0.03

speed                   GLfloat                 0.8
rotationSpeedModel      GLfloat                 2.0

scaleModel              Vector3                 0.09, 0.09, 0.09
positionModel           Vector3                 7.0, 0.0, -2.3
turnModel               Vector3                 0.0, -90.0, 0.0

LastTime                dd                      0

rotations               Vector3                 0.0, -90.0, 0.0

VK_W                    =                       0x57
VK_S                    =                       0x53
VK_A                    =                       0x41
VK_D                    =                       0x44
VK_E                    =                       0x45
VK_Q                    =                       0x51




KeyState                dd                      0