position                Vector3                 2.0, 2.0, -2.0
turn                    Vector3                 0.0, 0.0, 0.0
cursorPos               POINT
mouseSpeed              GLfloat                 0.03
speed                   GLfloat                 0.005
windowWidthH            GLfloat                 0
windowHeightH           GLfloat                 0
mapAngleX               GLfloat                 90.0
mapAngleZ               GLfloat                 90.0

VK_W                    =                       0x57
VK_S                    =                       0x53
VK_A                    =                       0x41
VK_D                    =                       0x44
VK_E                    =                       0x45
VK_Q                    =                       0x51