VK_W                    =                       0x57
VK_S                    =                       0x53
VK_A                    =                       0x41
VK_D                    =                       0x44
VK_E                    =                       0x45
VK_Q                    =                       0x51
VK_LBUTTON              =                       0x01


gameState               dd                      0

fShoot                  dd                      false
fFocus                  dd                      true

stdDamage                =                      30

keyState                dd                      0

lastDrawTime            dd                      0

mouseSpeed              GLfloat                 0.03


playerCnt               dd                      ?

lastRespawn             dd                      ?

