VK_W                    =                       0x57
VK_S                    =                       0x53
VK_A                    =                       0x41
VK_D                    =                       0x44
VK_E                    =                       0x45
VK_Q                    =                       0x51

KeyState                dd                      0

LastTime                dd                      0

mouseSpeed              GLfloat                 0.03