positionModel1           Vector3                 10.0, 0.0, -2.3
turnModel1               Vector3                 0.0, -90.0, 0.0
rotations1               Vector3                 0.0, -90.0, 0.0

positionModel2           Vector3                 10.0, 0.0, -23.5
turnModel2               Vector3                 0.0, 90.0, 0.0
rotations2               Vector3                 0.0, 90.0, 0.0

positionModel4           Vector3                 17.0, 0.0, -16.7
turnModel4               Vector3                 0.0, 90.0, 0.0
rotations4               Vector3                  0.0, 90.0, 0.0

positionModel3            Vector3                 3.0, 0.0, -10.0
turnModel3                Vector3                 0.0, -90.0, 0.0
rotation3                Vector3                   0.0, -90.0, 0.0