;Tank params
speed                   GLfloat                 0.8
rotationSpeedModel      GLfloat                 2.0

scaleModel              Vector3                 0.09, 0.09, 0.09
positionModel           Vector3                 7.0, 0.0, -2.3
turnModel               Vector3                 0.0, -90.0, 0.0

;Crosshair params
crosshair               dd                      ?
crosshairSize           dd                      ? 
crosshairOffs           Vector3                 0.0, 0.0, -1.0    
                
;Shooting params
shootPointOffs          Vector3                 0.0, 0.5, -2.25
