;Tank params
speed                   GLfloat                 0.8
rotationSpeedModel      GLfloat                 2.0

scaleModel              Vector3                 0.09, 0.09, 0.09


;Crosshair params
crosshair               dd                      ?
crosshairOffs           Vector3                 0.0, 11.0, -20.0    
                
;Shooting params
shootPointOffs          Vector3                 0.0, 5.55, -5.0  
shootAnimObj            dd                      ?
shootAnimOffs           Vector3                 0.0, 5.55, -20.0 
shootAnimTime           dd                      0


;test second tank
scaleTarget              Vector3                0.09, 0.09, 0.09



