struct Axes
       a1               Vector3
       a2               Vector3
       a3               Vector3
       a4               Vector3
       a5               Vector3
       a6               Vector3
       a7               Vector3
       a8               Vector3
       a9               Vector3
       a10              Vector3
       a11              Vector3
       a12              Vector3
       a13              Vector3
       a14              Vector3
       a15              Vector3
ends

axes    Axes

DISTANCE_FOR_CHECK_COLLISION            GLfloat         15.0