        playTxt         db      "PLAY", 0
        exitTxt         db      "EXIT", 0
        retTxt          db      "RETURN", 0
        menuTxt         db      "MENU",0
        onePlayerTxt    db      "1PLAYER ",0
        twoPlayersTxt   db      "2PLAYERS",0
        fourPlayersTxt  db      "4PLAYERS",0
        createGTxt      db      "HOST",0
        joinGTxt        db      "JOIN", 0
        emptyEditText   db      "               ",0
        stdEditText     db      "Input IP", 0
        connectTxt      db      "CONNECT", 0
        deathTxt        db      "YOU DEAD", 0
        waitTxt         db      "Wait for respown", 0